version: '3'
services:
  mysql:
    # image: mysql:5
    restart: always
    build:
        context: ./
        dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  sql-lint:
    build:
      context: ./
      dockerfile: ./ci/Dockerfile

volumes:
  mysql: ~
